# -*- coding: utf-8 -*-
"""QOLS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IegEe5ii-LyAYJhEQ0HAoPtfEOjnq7eS
"""

!pip install -q transformers datasets accelerate peft bitsandbytes sentencepiece

import os
import shutil
import subprocess

# Try to unmount Google Drive if already mounted
subprocess.run(["fusermount", "-u", "/content/drive"], stderr=subprocess.DEVNULL)

# Remove any leftover mount directories
shutil.rmtree("/content/drive", ignore_errors=True)
os.makedirs("/content/drive", exist_ok=True)

# Fresh mount
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

import os

BASE_DIR = "/content/drive/MyDrive/bangla_llm"
DATA_DIR = os.path.join(BASE_DIR, "data")
CKPT_DIR = os.path.join(BASE_DIR, "checkpoints")
FINAL_DIR = os.path.join(BASE_DIR, "final_model")

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(CKPT_DIR, exist_ok=True)
os.makedirs(FINAL_DIR, exist_ok=True)

print("Project directories ready:")
print(DATA_DIR)
print(CKPT_DIR)
print(FINAL_DIR)

from transformers import AutoTokenizer

MODEL_NAME = "Qwen/Qwen2.5-0.5B"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True,
    trust_remote_code=True
)

print("Tokenizer loaded")

from datasets import load_dataset

DATA_FILE = "/content/drive/MyDrive/bangla_llm/data/train.txt"

# AI4Bharat IndicCorpV2: Bangla split is "ben_Beng" under subset/config "indiccorp_v2"
ds = load_dataset(
    "ai4bharat/IndicCorpV2",
    "indiccorp_v2",
    split="ben_Beng",
    streaming=True
)

MAX_LINES = 200_000  # T4-safe

n = 0
with open(DATA_FILE, "w", encoding="utf-8") as f:
    for sample in ds:
        text = (sample.get("text") or "").strip()
        if text:
            f.write(text.replace("\n", " ") + "\n")
            n += 1
            if n >= MAX_LINES:
                break

print(f"Wrote {n} lines to {DATA_FILE}")

from datasets import load_dataset

DATA_FILE = "/content/drive/MyDrive/bangla_llm/data/train.txt"

dataset = load_dataset("text", data_files={"train": DATA_FILE})

def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        max_length=512,
        padding=False
    )

tokenized_ds = dataset.map(
    tokenize,
    batched=True,
    remove_columns=["text"]
)

print("Tokenization successful")
print(tokenized_ds)
print("Example tokenized item:", tokenized_ds["train"][0])

import torch
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

MODEL_NAME = "Qwen/Qwen2.5-0.5B"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

print("Model loaded in 4-bit")

from peft import LoraConfig, get_peft_model

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

import inspect
from transformers import TrainingArguments

CKPT_DIR = "/content/drive/MyDrive/bangla_llm/checkpoints"

sig = inspect.signature(TrainingArguments.__init__)
params = sig.parameters

args = dict(
    output_dir=CKPT_DIR,
    overwrite_output_dir=False,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    num_train_epochs=1,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=10,
    save_steps=50,
    save_total_limit=3,
    report_to="none",
    optim="paged_adamw_8bit",
)

# Handle version differences: evaluation_strategy vs eval_strategy
if "evaluation_strategy" in params:
    args["evaluation_strategy"] = "no"
elif "eval_strategy" in params:
    args["eval_strategy"] = "no"

training_args = TrainingArguments(**args)
print("TrainingArguments ready (compatible).")

import os

def get_latest_checkpoint(path):
    if not os.path.exists(path):
        return None
    ckpts = [
        os.path.join(path, d)
        for d in os.listdir(path)
        if d.startswith("checkpoint-")
    ]
    return max(ckpts, key=os.path.getmtime) if ckpts else None

resume_ckpt = get_latest_checkpoint(CKPT_DIR)
print("Resuming from:", resume_ckpt)

from transformers import Trainer, DataCollatorForLanguageModeling

# Causal LM collator (no MLM)
collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ds["train"],
    tokenizer=tokenizer,
    data_collator=collator,
)

trainer.train(resume_from_checkpoint=resume_ckpt)